kind: Deployment
apiVersion: apps/v1
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash-k8s-named
          image: logstash:7.2.0
          command: ["/bin/sh","-c"]
          args: ["/usr/share/logstash/bin/logstash -f /usr/share/logstash/config/logstash-config-update.conf"]
          volumeMounts:
            - name: vm-config
              mountPath: /usr/share/logstash/config
      volumes:
        - name: vm-config
          configMap:
            name: logstash-config
            items:
              - key: logstash-config
                path: logstash-config-update.conf