apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "redis-service"
  name: redis
spec:
  ports:
    - port: 6379
      protocol: "TCP"
      targetPort: 6379
  selector:
    app: "redis"
  type: "LoadBalancer"
